### ISSUE TITLE
Project fails to build on Android Studio 4.2 Beta

### ISSUE THREAD

**Issue by MarKco** [iSoron/uhabits#681]
Hello,
I'd like to contribute to uhabits. In order to check if my Android skills are good enough for you I tried to build the Android project but couldn't manage to make it. I tried clean-and-rebuild, command-line build, re-syncing with gradle files but couldn't make it past this error:

```
/.../uhabits/android/uhabits-android/build/tmp/kapt3/stubs/debug/org/isoron/uhabits/sync/SyncManager.java:30: error: cannot find symbol
    private final ImportDataTaskFactory importDataTaskFactory = null;
                  ^
```

Wha'ts odd is that opening SyncManager and getting to the ImportDataTaskFactory class works. The file is correctly retrieved. I can see both files are in the build subfolder, are they generated files? I tried deleting the content of the build folder, still I get the same error while building.

Did you ever get such error? Would you mind to help me?

Thank you
Marco

![image](https://user-images.githubusercontent.com/1422362/102884895-b7683900-4452-11eb-8d0c-769e1f6863b3.png)

**Comment by iSoron** [comment]
Hi @MarKco, thank you for your interest in helping you. Could you delete your existing repository, then follow the command line instructions in [BUILD.md](https://github.com/iSoron/uhabits/blob/dev/docs/BUILD.md#build-from-the-command-line)?

If you are using Android Studio, please make sure that you ignore the suggestions to update plugins/dependencies.

**Comment by MarKco** [comment]
Hello iSoron,
thank you for your reply.

I cloned the repository without forking and performed the gradlew build from command line. I got the following error:

```
/home/marco/.../uhabits/android/uhabits-android/build/tmp/kapt3/stubs/debug/org/isoron/uhabits/activities/habits/list/views/HabitCardListView.java:21: error: cannot find symbol
    private final HabitCardViewFactory cardViewFactory = null;
                  ^
  symbol:   class HabitCardViewFactory
  location: class HabitCardListView/home/marco/.../uhabits/android/uhabits-android/build/tmp/kapt3/stubs/debug/org/isoron/uhabits/activities/habits/list/views/HabitCardListView.java:86: error: cannot find symbol
    HabitCardViewFactory cardViewFactory, @org.jetbrains.annotations.NotNull()
    ^
```

I tried opening the project from Android Studio, of course ignoring every plugin/dependencies update warning. Tried to build, got the same error. Performed a clean/rebuild, still same error.

Please notice I'm on the dev branch. Tried to build on master, got another error

```
/home/marco/.../uhabits/android/uhabits-android/src/main/java/org/isoron/uhabits/activities/about/AboutModule.java:25: error: reference to Module is ambiguous
@Module
 ^
  both class dagger.Module in dagger and class java.lang.Module in java.lang match
```

Can I perform some other tests in order to help?

**Comment by iSoron** [comment]
Could you post the output of `java -version`? Here is mine, for example:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```
If you are using anything newer than Java 8, please downgrade. Android has issues with newer SDKs. If you are using Ubuntu/Debian, the package you want for java is `openjdk-8-jdk-headless`.

**Comment by MarKco** [comment]
Thank you iSoron. This is what I had
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.10, mixed mode, sharing)
```

On your suggestion I downgraded to Java 8. Now everything builds fine from command line. Shame on me. -.-

What I still can't manage to do is to build on Android Studio. I tried to change the JDK location in the Project Structure settings but it seems like Android Studio already provides its own set of JDKs

![image](https://user-images.githubusercontent.com/1422362/103223050-b4bf8500-4925-11eb-982d-e210976ef6a8.png)

Also, it seems like a Java 11 SDK is required because if I change the path to the java-8-openjdk I get the following dialog

![image](https://user-images.githubusercontent.com/1422362/103223249-1a137600-4926-11eb-800c-2b3d04c783e0.png)

Do you happen to know if I'm supposed to change Android Studio JDK path as well and how to do so in order to build the app?

Thank you
Marco

**Comment by iSoron** [comment]
No problem, Marco. Thanks for confirming that the project fails to build with JDK 11. What version of Android Studio are you using? Is this a canary/beta version? Could you try the stable version?

**Comment by MarKco** [comment]
And of course you were right again, Alinson. I was using 4.2 beta 2. Installed Android Studio stable 4.1.1, everything built fine.

Now, chances are that you don't want a developer who apparently can't properly configure Android Studio and Java SDK working for the project :-D Anyways I'd like to help :-) so if you don't ban me I can start looking at the smaller issues and see if I can be of some use for the uhabits community. I've been using the app for a year now and I really love it, I'd be honored to do my best to help.

**Comment by iSoron** [comment]
I would actually consider this a bug: we should be able to run the project on Android Studio 4.2 beta without errors, so thanks for bringing it up. Pull requests fixing this are very welcome.

As for other suggestions on things to work on, I am currently reorganizing our issue tracker to clarify what are the ongoing development tasks. For example, we are currently converting the project to Kotlin (#685). I am planning to create a few more of these issues in the following days. Besides the issues, please also have a look at the [top feature requests from users](https://github.com/iSoron/uhabits/discussions?discussions_q=sort%3Atop). If you see any feature you would be interested in working on, feel free to open a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to start a discussion about the implementation.

**Comment by MarKco** [comment]
I can confirm that now I can open and run the project on Android Studio 4.2 beta without any issue. Thank you!
